### ISSUE TITLE
Maven repository down

### ISSUE THREAD

**Issue by magistermaks** [Epoxide-Software/Extremely-Simple-Storage#2]
The gradle example on the main page doesn't work as the the listed maven (http://maven.epoxide.xyz) is no longer available, has it been moved somewhere else or is it no longer supported?

**Comment by Darkhax** [comment]
Hello,

Unfortunately the Epoxide group has been effectively disbanded and our projects are no longer being maintained or supported. If you are still interested in using this library I would recommend bundling it directly. The library consists of only two relatively small classes and have no additional dependencies beyond the standard Java API so it should be a simple drop in.

**Comment by magistermaks** [comment]
Ok, thanks for the response!

**Comment by zpiddock** [comment]
If you do want a hosted version, I have forked the project and published a build on my maven repo. 
Updated the readme to reflect this.
You can view [here](https://github.com/ShadowChild/Extremely-Simple-Storage/)
